CREATE RULE rl_precoLivro AS @VALOR >= 0 -- CRIA UMA REGRA QUE PODE SER APLICADA A ALGUM CAMPO DA TABELA

EXECUTE SP_BINDRULE rl_precoLivro, 'tbl_Livros.PrecoLivro' -- ASSOCIA A REGRA A TABELA E AO CAMPO INFORMADO

SELECT * FROM tbl_Livros

INSERT INTO tbl_Livros
VALUES ('ASPNET', 1234587, GETDATE(), -10, 3, 4) -- NÃO SERÁ POSSIVEL POIS A REGRA SO 
-- PERMITE QUE O PRECO DO LIVRO SEJA ACIMA OU IGUAL A 0
