SELECT * FROM tbl_LivroVenda


SELECT NomeLivro AS Livro, PrecoLivro AS Preco, IdAutor As Autor -- SELECIONA AS COLUNAS INFORMADAS E COLOCA OS APELIDOS
INTO tbl_LivroVenda -- INSERE OS DADOS DA CONSULTA NA TABELA INFORMADA
FROM tbl_Livros -- PEGA OS DADOS DA TABELA INFORMADA
WHERE IdLivro = 100 -- ONDE O ID FOR IGUAL AO INFORMADO
