SELECT * FROM tbl_Livros 
WHERE PrecoLivro BETWEEN 70.00 AND 80.00 -- RETORNA OS DADOS QUE TEM OS VALORES ENTRE 70 E 80

SELECT * FROM tbl_Autores
WHERE IdAutor BETWEEN 1 AND 3 -- RETORNA OS DADOS QUE TEM OS VALORES ENTRE 1 E 3 
OR IdAutor BETWEEN 4 AND 6 -- OU OS VALORES ENTRE 4 E 6