SELECT * FROM tbl_Editoras 
WHERE IdEditora IN (1, 2, 3) -- RETORNA OS REGISTROS COM OS IDS 1 2 E 3

SELECT * FROM tbl_Editoras 
WHERE IdEditora NOT IN (1, 2, 3) -- RETORNA OS REGISTROS QUE NÃO TEM OS IDS 1 2 E 3
