SELECT * FROM tbl_Livros AS l
LEFT JOIN tbl_Autores AS a ON a.IdAutor = l.IdAutor -- RETORNA TODOS OS REGISTROS MESMO QUE NÃO HAJA CORRESPONDÊNCIA NA TABELA À DIREITA

SELECT * FROM tbl_Livros AS l 
RIGHT JOIN tbl_Autores AS a ON a.IdAutor = l.IdAutor -- RETORNA TODOS OS REGISTROS MESMO QUE NÃO HAJA CORRESPONDÊNCIA NA TABELA À ESQUERDA
WHERE a.IdAutor IS NULL -- RETORNA OS REGISTROS DA TABELA A DIREITA QUE O ID É NULL
