SELECT * FROM fn_helpcollations() -- PARA VER OS TIPOS DE AGRUPAMENTOS DISPONIVEIS

SELECT SERVERPROPERTY('Collation') -- PARA VER O ESQUEMA DE COLAÇÃO UTILIZADO PELO SERVER

SELECT DATABASEPROPERTYEX('db_CursoSqlServer' , 'Collation') -- PARA VER O ESQUEMA DE COLAÇÃO UTILIZADO PELO BANCO DE DADOS

ALTER DATABASE db_CursoSqlServer -- ALTERA O BANCO DE DADOS
COLLATE Latin1_General_CI_AS -- ALTERA O COLLATE DO BANCO DE DADOS

SELECT * FROM tbl_Livros
ORDER BY NomeLivro 
COLLATE ICelandic_CI_AI -- TRAS A CONSULTA COM A COLLATE ICelandic