BACKUP DATABASE db_CursoSqlServer -- REALIZA O BACKUP DO BANCO DE DADOS ESPECIFICADO
TO DISK = 'C:\SQL\SqlServer.bak' -- CAMINHO ONDE O BACKUP SERÁ CRIADO
-- WITH FORMAT -- FORMATA O BACKUP 

DROP DATABASE db_CursoSqlServer

SELECT * FROM tbl_Livros