SELECT * FROM tbl_Livros AS l
FULL JOIN tbl_Autores AS a ON a.IdAutor = l.IdAutor -- RETORNA TODOS OS REGISTROS MESMO QUE NÃO HAJA CORRESPONDÊNCIA EM NENHUMA
-- DAS TABELAS
WHERE l.IdAutor IS NULL OR a.IdAutor IS NULL -- RETORNA APENAS OS REGISTROS QUE NÃO TEM CORRESPONDÊNCIA