SELECT COUNT(*) AS Quatidade FROM tbl_Autores -- RETORNA A QUANTIDADE DE REGISTROS DA TABELA

SELECT MAX(PrecoLivro) AS MaiorValor FROM tbl_Livros -- RETORNA O MAIOR VALOR DA COLUNA

SELECT MIN(PrecoLivro) AS MenorValor FROM tbl_Livros -- RETORNA O MENOR VALOR DA COLUNA

SELECT AVG(PrecoLivro) AS MediaValor FROM tbl_Livros -- RETORNA A MEDIA DOS VALORES DA COLUNA

SELECT SUM(PrecoLivro) AS SomaValor FROM tbl_Livros -- RETORNA A SOMA DOS VALORES DA COLUNA