SELECT * FROM tbl_Livros
ORDER BY NomeLivro ASC -- SELECT COM ORDERNAÇÃO CRESCENTE POR PADRÃO JA VEM CRESCENTE

SELECT * FROM tbl_Livros
ORDER BY NomeLivro DESC -- -- SELECT COM ORDERNAÇÃO DECRESCENTE