SELECT * FROM tbl_Livros -- LISTA TODOS OS DADOS DA TABELA

ALTER TABLE	tbl_Livros -- ALTERA A TABELA
DROP COLUMN IdAutor	 -- EXCLUI UM CAMPO DA TABELA


ALTER TABLE nomeTabela 
DROP CONSTRAINT nomeConstraint -- EXCLUIR A CONSTRAINT

ALTER TABLE tbl_Livros 
ADD IdAutor SMALLINT NOT NULL CONSTRAINT fk_IdAutor
FOREIGN KEY (IdAutor) REFERENCES tbl_Autores -- ADICIONA UMA NOVA COLUNA COMO CHAVE ESTRANGEIRA 

ALTER TABLE tbl_Livros
ADD IdEditora SMALLINT NOT NULL CONSTRAINT fk_IdEditora 
FOREIGN KEY (IdEditora) REFERENCES tbl_Editoras


CREATE TABLE Clientes(
IdCliente SMALLINT NOT NULL,
Nome VARCHAR(80) NOT NULL
)

ALTER TABLE tbl_Clientes 
ADD PRIMARY KEY(IdCliente) -- ADICIONA UMA CHAVE PRIMARY A TABELA CASO NÃO TENHA


CREATE TABLE tbl_testes(
IdTeste SMALLINT NOT NULL
)

DROP TABLE tbl_testes -- EXCLUI A TABELA