USE db_CursoSqlServer


-- CRIAR TABELA LIVRO
CREATE TABLE tbl_Livro -- COMANDO PARA CRIAR A TABELA
(IdLivro SMALLINT PRIMARY KEY IDENTITY(100, 1), -- COMANDO PARA CRIAR A COLUNA E DEFINIR COMO CHAVE PRIMARIA AUTO INCREMENTO COMEÇANDO DO 100 DE UM E UM
NomeLivro VARCHAR(50) NOT NULL, -- COMANDO PARA CRIAR A COLUNA COM OBRIGAÇÃO DE PREENCHIMENTO DO DADO
ISBN VARCHAR(30) NOT NULL UNIQUE, -- COMANDO PARA CRIAR A COLUNA COM OBRIGAÇÃO DE PREENCHIMENTO DO DADO E NÃO PERMITIR DUPLICAÇÃO
IdAutor SMALLINT NOT NULL, 
DataPublicacao DATETIME NOT NULL,
PrecoLivro MONEY NOT NULL) 

-- CRIAR TABELA AUTORES
CREATE TABLE tbl_Autores(
IdAutor SMALLINT PRIMARY KEY, 
NomeAutor VARCHAR(50),
SobreNome VARCHAR(70),
)

-- CRIAR TABELA EDITORAS
CREATE TABLE tbl_Editoras(
IdEditoras SMALLINT PRIMARY KEY IDENTITY,
NomeEditora VARCHAR(50) NOT NULL
)

sp_help tbl_Editoras -- COMANDO PARA OBTER INFORMAÇÕES SOBRE A TABELA