Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/10/2021
Var
// Seção de Declarações das variáveis 
aux : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


para aux de 10 ate 1000 passo 10 faca

     escreval(aux)

fimpara

Fimalgoritmo