Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/09/2021
Var
// Seção de Declarações das variáveis 
a, b, aux: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

a <- 5
b <- 10
aux <- b
b <- a
a <- aux

Escreval("A =",a, ", B = ",b)



Fimalgoritmo